# Generated by Django 3.1 on 2020-10-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_searchs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searchs',
        ),
    ]
