# Generated by Django 3.1 on 2020-10-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_searchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducation',
            name='education_type',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeelanguage',
            name='emplooyee',
        ),
        migrations.RemoveField(
            model_name='employeelanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='employeelanguage',
            name='language_level',
        ),
        migrations.DeleteModel(
            name='EducationType',
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
        migrations.DeleteModel(
            name='EmployeeExperience',
        ),
        migrations.DeleteModel(
            name='EmployeeLanguage',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='LanguageLevel',
        ),
    ]
